### PR TITLE
Straight back

### LINKED ISSUE #24: Going backwards doesn't work
@jrlandau reported that goals behind don't work.

Question: should it handle this as a special case and actually move backwards, or do the arctan planner thing and rotate to face the goal and drive towards it?  If it moves backwards, then a front-facing LIDAR does not provide obstacle detection.

Definition of done:
Backwards goals result in behavior that considered reasonable by consensus.

### PR DESCRIPTION
**Pull request by jim-v**
Closes #24

### CODE REVIEW

**Review by jrlandau — APPROVED** [review]

File: src/move_basic.cpp [hunk 1]
```diff
@@ -173,6 +175,9 @@ MoveBasic::MoveBasic(): tfBuffer(ros::Duration(30.0)),
     // how long to wait for an obstacle to disappear
     nh.param<double>("obstacle_wait_limit", obstacleWaitLimit, 10.0);
 
+    // Reverse distances for which rotation won't be performed
+    nh.param<double>("straight_back_threshold", straightBackThreshold, 0.5);
```
Comment (rohbotics) [inline src/move_basic.cpp]: 'straight_back' is a misleading name, it should be backup or reverse instead.

File: src/move_basic.cpp [hunk 2]
```diff
@@ -367,6 +372,16 @@ void MoveBasic::executeAction(const move_base_msgs::MoveBaseGoalConstPtr& msg)
...
     pathPub.publish(path);
 
+    tf2::Transform goalInBase;
+    if (!transformPose(frameId, "base_link", goal, goalInBase)) {
+         ROS_WARN("Cannot determine robot pose for linear");
+         return;
+    }
+    tf2::Vector3 linear = goalInBase.getOrigin();
+    ROS_INFO("Forward = %f", linear.x());
+    bool straightBack = (linear.x() > -straightBackThreshold && linear.x() < 0.0);
```
Comment (rohbotics) [inline src/move_basic.cpp]: same with the variable name.

Also it may be more readable if you rearrange the expression to be like `-threshold < X && X < 0`.

File: src/move_basic.cpp [hunk 3]
```diff
@@ -378,6 +393,14 @@ void MoveBasic::executeAction(const move_base_msgs::MoveBaseGoalConstPtr& msg)
         tf2::Vector3 offset = goalInBase.getOrigin();
         if (offset.length() != 0.0) {
             double requestedYaw = atan2(offset.y(), offset.x());
+            if (straightBack) {
+                if (requestedYaw > 0) {
```
Comment (rohbotics) [inline src/move_basic.cpp]: Should be 0.0

File: src/move_basic.cpp [hunk 4]
```diff
@@ -621,13 +639,14 @@ bool MoveBasic::moveLinear(double requestedDistance)
...
-        //ROS_INFO("%f %f %f", distTravelled, distRemaining, velocity);
-
-        if (distTravelled > requestedDistance - linearTolerance) {
+        if (std::abs(distTravelled) > std::abs(requestedDistance) - linearTolerance) {
             velocity = 0;
             done = true;
             ROS_INFO("Done linear, error %f meters", distRemaining);
         }
+        if (requestedDistance < 0) { 
+            velocity = -velocity;
```
Comment (rohbotics) [inline src/move_basic.cpp:649]: Does it make sense to have a separate velocity limit when going backward?

**Review by rohbotics — CHANGES_REQUESTED** [review]

File: src/move_basic.cpp (hunk 4 above)
Comment (jim-v) [reply src/move_basic.cpp:649]: I don't think so.

File: src/move_basic.cpp (hunk 3 above)
Comment (jim-v) [reply src/move_basic.cpp]: Changed

File: src/move_basic.cpp (hunk 1 above)
Comment (jim-v) [reply src/move_basic.cpp]: Changed

File: src/move_basic.cpp (hunk 2 above)
Comment (jim-v) [reply src/move_basic.cpp]: Changed

**Comment by rohbotics** [comment]
@jim-v looks like you forgot to push

**Review by rohbotics — APPROVED** [review]
